// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ghost.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Containers with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Containers) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Containers with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ContainersMultiError, or
// nil if none found.
func (m *Containers) ValidateAll() error {
	return m.validate(true)
}

func (m *Containers) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ContainersMultiError(errors)
	}

	return nil
}

// ContainersMultiError is an error wrapping multiple validation errors
// returned by Containers.ValidateAll() if the designated constraints aren't met.
type ContainersMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ContainersMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ContainersMultiError) AllErrors() []error { return m }

// ContainersValidationError is the validation error returned by
// Containers.Validate if the designated constraints aren't met.
type ContainersValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContainersValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContainersValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContainersValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContainersValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContainersValidationError) ErrorName() string { return "ContainersValidationError" }

// Error satisfies the builtin error interface
func (e ContainersValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContainers.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContainersValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContainersValidationError{}

// Validate checks the field values on Containers_Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Containers_Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Containers_Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Containers_RequestMultiError, or nil if none found.
func (m *Containers_Request) ValidateAll() error {
	return m.validate(true)
}

func (m *Containers_Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return Containers_RequestMultiError(errors)
	}

	return nil
}

// Containers_RequestMultiError is an error wrapping multiple validation errors
// returned by Containers_Request.ValidateAll() if the designated constraints
// aren't met.
type Containers_RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Containers_RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Containers_RequestMultiError) AllErrors() []error { return m }

// Containers_RequestValidationError is the validation error returned by
// Containers_Request.Validate if the designated constraints aren't met.
type Containers_RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Containers_RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Containers_RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Containers_RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Containers_RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Containers_RequestValidationError) ErrorName() string {
	return "Containers_RequestValidationError"
}

// Error satisfies the builtin error interface
func (e Containers_RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContainers_Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Containers_RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Containers_RequestValidationError{}

// Validate checks the field values on Containers_Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Containers_Response) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Containers_Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Containers_ResponseMultiError, or nil if none found.
func (m *Containers_Response) ValidateAll() error {
	return m.validate(true)
}

func (m *Containers_Response) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return Containers_ResponseMultiError(errors)
	}

	return nil
}

// Containers_ResponseMultiError is an error wrapping multiple validation
// errors returned by Containers_Response.ValidateAll() if the designated
// constraints aren't met.
type Containers_ResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Containers_ResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Containers_ResponseMultiError) AllErrors() []error { return m }

// Containers_ResponseValidationError is the validation error returned by
// Containers_Response.Validate if the designated constraints aren't met.
type Containers_ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Containers_ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Containers_ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Containers_ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Containers_ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Containers_ResponseValidationError) ErrorName() string {
	return "Containers_ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e Containers_ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContainers_Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Containers_ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Containers_ResponseValidationError{}
